name: CI

# Trigger on any push or pull requests
on:
  push:
  pull_request:
  pull_request_target:

jobs:
  run-tests:
    strategy:
      # Do not fail fast, so we can see all errors from the unit/integration tests
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.9"
          - "3.10"
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dev packages
        run: python -m pip install -r requirements-dev.txt

      - name: Install default dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Install coppafish
        run: python -m pip install .

      - name: Verify coppafish import
        run: python -Ic "import coppafish"

      - name: Run default unit tests
        run: pytest -m "not integration and not manual" --cov=coppafish --cov-report term

      - name: Run default integration tests
        run: pytest -m "integration and not manual" --cov=coppafish --cov-report term
